var urlpatterns = {
    'skill-template': 'consultant/skillsassessments/templates/',
    'messages': 'frontend/messages/',
    'api-countries': 'frontend/countries/',
    'api-countries2': 'frontend/countries2/',
    'api-cities': 'frontend/cities/',
    'feedback': 'frontend/feedback/',
    'api-organization-detail': "diagnosis/organizations/%s/",
    'api-organization-add': 'diagnosis/organizations/',
    // Services URL's
    'create-service': 'project/create-service/',
    // Project Url
    'project-edit': 'project/%s/edit/',
    // Sprint urls
    'project-create-team': "project/%s/team/add/",
    'project-edit-team': "project/%s/team/edit/%s/",
    'send-email-team': "project/%s/team/send-email/",
    'sprint-edit': 'sprint/%s/edit/',
    'sprint-add': 'sprint/add/',
    'project-change-status': 'project/%s/change-status/',
    'sprint-exo-project-list': 'sprint/%s/exoprojects',
    'folder-detail': 'files/%s/folders/%s',
    'folder-list': 'files/%s/folders/folder-subfolder/%s',
    'file-list': 'files/%s/folders/folder-files/%s',
    'folder-add': 'files/%s/folders/%sfolder-add/',
    'file-add': 'files/%s/folders/%s/file-add/',
    'folder-path': 'files/%s/folders/%sfolder-path/',
    'file-project-latest': 'files/%s/folders/latest-files/',
    'file-edit': 'files/%s/folders/%s/file-edit/%s/',
    'file-upload': 'files/%s/file-upload/',
    'resource-upload': 'files/resource-upload/',
    'file-user-latest': 'files/user/',
    'exo-project-files-related': 'relation/project/%s/exo-projects/%s/files/',
    'exo-project-remove-file': 'relation/project/%s/exo-projects/%s/files/%s/',
    'consultant-autocomplete': 'consultant/consultant-autocomplete/',
    'api-survey-template': 'diagnosis/survey-template/',
    'api-survey-answers': 'diagnosis/survey-answers/%s/',
    'api-survey-fill': 'diagnosis/survey-fill/%s/',
    'api-folder-autocomplete': 'files/%s/autocomplete/folders/',
    'api-search-nodes': 'files/%s/autocomplete/nodes/',
    'api-report-dynamic-complete': 'diagnosis/reports/compare/complete/',
    'api-validate-password': 'profile/validate-password/',
    'api-edit-image-user-profile': 'profile/%s/update-image-profile/',
    // Autocomplete for Area
    'api-autocomplete-area': 'diagnosis/autocomplete/area/%s/',
    'areas': 'diagnosis/areas/',
    // Task Endpoints
    'api-task-permissions-types': 'task/%s/permission/',
    'api-task-permissions-objects': 'task/%s/permission/%s/%s/',
    'task-project': 'task/%s/',
    'task-create': 'task/%s/add/',
    'task-edit': 'task/%s/edit/%s/',
    'task-deliver': 'task/%s/deliver/%s/',
    'task-user': 'task/user/',
    'task-files-related': 'relation/project/%s/tasks/%s/files/',
    'task-remove-file': 'relation/project/%s/tasks/%s/files/%s/',
    // Tickets
    'request-collaborator-create': 'ticket/sprint/%s/request-collaborator/add/',
    'request-collaborator-edit': 'ticket/sprint/%s/request-collaborator/edit/%s/',
    'request-collaborator-accept': 'ticket/sprint/%s/request-collaborator/accept/%s/',
    'request-collaborator-schedule': 'ticket/sprint/%s/request-collaborator/schedule/%s/',
    'request-collaborator-complete': 'ticket/sprint/%s/request-collaborator/complete/%s/',
    'request-collaborator-remove': 'ticket/sprint/%s/request-collaborator/remove/%s/',
    'request-collaborator-request-again': 'ticket/sprint/%s/request-collaborator/request-again/%s/',
    // Skill Assessment
    'languages': 'core/languages/',
    'skill-assessment-detail':'public-skill-assessment/skillsassessments/%s/',
    'invitation-skill-accept':'public-skill-assessment/accept-invitation/%s/',
    // Invitations
    'preview-invitation': 'invitation/preview/',
    'resend-invitation': 'invitation/resend/%s/',
    'resend-user-invitation': 'invitation/resend-user/%s/',
    // Industry Api
    'industry-select2': 'industries/list/select2/',
    // Roles
    'roles': 'roles/',
    'consultant-roles': 'relation/consultant/%s/roles/',
    'consultant-roles-detail': 'relation/consultant/%s/roles/%s/',
    // Training Session
    'training-session': 'learning/training-session/',
    'consultant-trained': 'relation/consultant/%s/trained/',
    'consultant-toggle-web-status': 'consultant/toggle-web-status/%s/%s/',
    'consultant-toggle-exo-certified': 'consultant/exo-certification/%s/',
    'consultant-trained-detail': 'relation/consultant/%s/trained/%s/',
    'reactive-consultant': 'consultant/reactivate/%s/',
    // User Preferences
    'add-order': 'user-preferences/%s/order/add/',
    'user-section-preference': 'user-preferences/%s/sections/',
    'section-fields': 'user-preferences/%s/fields/',
    // ExO consultant in project
    'exo-consultant-project-list': 'relation/project/%s/roles/',
    'exo-consultant-project-detail': 'relation/project/%s/roles/%s/',
    'user-roles': 'relation/project/%s/user_roles/',
    'user-roles-detail': 'relation/project/%s/user_roles/%s/',
    'project-assignment-change-status': 'project/%s/assignment/change-status/%s/',
    'resources-list': 'files/resources/resources/',
    'resources-add-tag': 'files/resources/resources/%s/tag-add/',
    'resources-remove-tag': 'files/resources/resources/%s/tag-remove/',
    'send-email': 'mail/send-email/%s/',
    // Forum
    'forum-generate-statistic': 'project/%s/forum/generate-statistic/',
    'forum-request-deploy': 'project/%s/forum/request-deploy/'
};
